### ISSUE TITLE
docs: decide how to handle the g8 templates

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko-http#124]
* do we continue with the existing theIterators templates?
* if so, should we change how we document the templates in the pekko-http docs (eg moving them to the Examples and Extensions page)
* do we create Pekko specific ones? This might have implications in terms of having the add license headers, come up with release processes, etc.

**Comment by luksow** [comment]
Hi, just to record it here, we - Iterators - are committed to help in any relevant way with the templates. For now, we'll do our best to maintain them.

**Comment by pjfanning** [comment]
we have https://github.com/apache/pekko-http-quickstart-java.g8/ and https://github.com/apache/pekko-http-quickstart-scala.g8/
