### ISSUE TITLE
[docs] the link to the incubator svg in our footer is broken on some pages

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko-http#482]
https://pekko.apache.org/docs/pekko-http/current/introduction.html is fine
it links to
https://pekko.apache.org/docs/pekko-http/current/assets/images/apache-incubator.svg

https://pekko.apache.org/docs/pekko-http/current/client-side/http2.html has wrong link
it links to
https://pekko.apache.org/docs/pekko-http/current/client-side/assets/images/apache-incubator.svg

Note the stray `/client-side` in the image URL.

This looks like a general problem when we nest our docs - that the link to the apache-incubator.svg in the footer includes a stray dir in the path. The following link is for a doc generated in the incubator-pekko repo.

https://pekko.apache.org/docs/pekko/current/discovery/index.html
links to
https://pekko.apache.org/docs/pekko/current/discovery/assets/images/apache-incubator.svg

**Comment by pjfanning** [comment]
@samueleresca this might be a pre-existing issue but is there a chance that the recent changes to our pekko-sbt-paradox and pekko-site setup could be an issue?

**Comment by pjfanning** [comment]
I suspect that this is a long running issue. I tried building with the pekko-http docs locally using the latest pekko-sbt-paradox snapshot but had the same issue.

I would like to change the link in footer.st to be an absolute URL to avoid the need to worry about the nesting of the docs.

Just link to https://pekko.apache.org/assets/images/apache-incubator.svg

**Comment by pjfanning** [comment]
I will retry 1.0.0+10-9676045b-SNAPSHOT but it did not seem to work as expected for me. I will double check.

**Comment by pjfanning** [comment]
@samueleresca I tried that again and it worked. I'll close my PR.

**Comment by samueleresca** [comment]
@pjfanning Do we have any plan for kicking off the release of `pekko-sbt-paradox`? I can help in case

**Comment by pjfanning** [comment]
My hope is that we can win a vote to become a TLP. We would then need to remove the Incubator references and release the paradox code. Even if we fail, we should do a paradox release - I just want to wait to see if can win the vote first.
