### ISSUE TITLE
API doc links broken

### ISSUE THREAD

**Issue by mpartel** [apache/pekko-http#493]
Both "API Documentation" links on https://pekko.apache.org/docs/pekko-http/current/reference.html are broken.

**Comment by pjfanning** [comment]
We'll need to fix that. In the meantime, see https://pekko.apache.org/modules.html. It's links work.

**Comment by pjfanning** [comment]
the links are fixed now in https://pekko.apache.org/docs/pekko-http/snapshot/reference.html#api-documentation

Will need to backport to 1.0.x branch to get current and 1.0 docs fixed.
